stabilizers:
  # One stabilizer on each InvertedResidual
  - filter:
      typename: InvertedResidual
    module:
      _target: instant_video_models.stabilizers.controlled_conv_stabilizer.ControlledConvStabilizer
      conv_kernel_size: 3
      exclude_feature_inputs: false
      final_bias_init: -4.0
      fusion_kernel_size: 1
      hidden_layers: 2
      hook_target: output
      internal_channels: 64
      interpolate_mode: bilinear
    links:
      - location: model.controller_backbone
        name: controller_backbone

    # Required for parameters to be visible
    registration_name: stabilizer

  # Stabilizers on some head/classifier blocks and the model output
  - filter:
      name:
        - model.classifier.aspp

        # Sequential modules don't work with hooks, so use their last layers
        - model.classifier.project.2
        - model.classifier.classifier.3

        # Model output
        - class_adapter
    module:
      _target: instant_video_models.stabilizers.controlled_conv_stabilizer.ControlledConvStabilizer
      conv_kernel_size: 3
      exclude_feature_inputs: false
      final_bias_init: -4.0
      fusion_kernel_size: 1
      hidden_layers: 2
      hook_target: output
      internal_channels: 64
      interpolate_mode: bilinear
    links:
      - location: model.controller_backbone
        name: controller_backbone

    # Required for parameters to be visible
    registration_name: stabilizer

controllers:
  # Backbone
  - filter:
      name: model
    module:
      _target: instant_video_models.controllers.conv_backbone.ConvBackbone
      conv_kernel_size: 3
      hidden_layers: 6
      hook_target: inputs
      internal_channels: 32
    pre_hook: true

    # Required for parameters to be visible
    registration_name: controller_backbone
