_defaults:
  - ./_defaults_train_stabilizers.yml
  - configs/stabilizers/nafnet/spatial_ema_stabilizer.yml
_remove:
  - input_transform

# Use lambda to create a subdir instead of appending to the name.
_name: train_spatial_ema_stabilizer_chunk_drop
_output_dir: outputs/${_config_dir}/${_name}/${lambda}/${_datetime}
checkpoint_search_path: ${_original_dir}/outputs/${_config_dir}/${_name}/${lambda}

input_transform:
  _target: torchvision.transforms.Compose
  transforms:
    - _target: stability.transforms.gaussian_noise.GaussianNoise
      sigma: 0.1
    - _target: stability.transforms.chunk_drop.ChunkDrop
      chunk_size: 8
      drop_ratio: 0.1

lambda: 0.2

# TODO: Try doubling the number of epochs (keeping lr the same)
epochs: 20
optimizer:
  lr: 1e-4
scheduler:
  _target: torch.optim.lr_scheduler.MultiStepLR
  milestones: [ 10, 15 ]
  gamma: 0.1
