_defaults:
  - ./train_spatial_ema_stabilizer_elastic_transform.yml
  - configs/stabilizers/nafnet/controlled_ema_stabilizer_composable.yml

_name: train_spatial_ema_stabilizer_elastic_transform_composable
