#!/usr/bin/env python3

# This script compares the results generated by validate_adain_original.sh and
# validate_adain_ours.py.

from pathlib import Path

from torchvision.io import read_image


def main():
    output_dir = Path("outputs", "validate_adain")
    original = read_image(str(output_dir / "original.png")).int()
    ours = read_image(str(output_dir / "ours.png")).int()
    print(f"Max deviation (scale 0-255): {(original - ours).abs().max():.4g}")
    print(f"Fraction deviated: {(original - ours).count_nonzero()} / {ours.numel()}")


if __name__ == "__main__":
    main()
