stabilizers:
  # One stabilizer on each Conv2d layer
  - filter:
      typename: Conv2d
      neg_regex: controller_backbone
    module:
      _target: stability.stabilizers.controlled_conv_ema_stabilizer.ControlledConvEMAStabilizer
      conv_kernel_size: 3
      final_bias_init: -4.0
      fusion_kernel_size: 1
      hidden_layers: 2
      hook_target: output
      internal_channel_ratio: null
      internal_channels: 64
      interpolate_mode: bilinear
      skip_connection: false
    links:
      - location: controller_backbone
        name: controller_backbone

    # Required for parameters to be visible
    registration_name: stabilizer

  # One stabilizer on each Linear layer (found in the global net)
  - filter:
      typename: Linear
      neg_regex: controller_backbone
    module:
      _target: stability.stabilizers.controlled_linear_ema_stabilizer.ControlledLinearEMAStabilizer
      final_bias_init: 4.0
      hidden_layers: 2
      hook_target: output
      internal_channel_ratio: null
      internal_channels: 256
      pool_backbone_output: true
      skip_connection: false
    links:
      - location: controller_backbone
        name: controller_backbone

    # Required for parameters to be visible
    registration_name: stabilizer

  # One stabilizer on the output
  - filter:
      name: ''
      neg_regex: controller_backbone
    module:
      _target: stability.stabilizers.controlled_conv_ema_stabilizer.ControlledConvEMAStabilizer
      conv_kernel_size: 3
      final_bias_init: -4.0
      fusion_kernel_size: 1
      hidden_layers: 2
      hook_target: output
      internal_channel_ratio: null
      internal_channels: 64
      interpolate_mode: bilinear
      skip_connection: false
    links:
      - location: controller_backbone
        name: controller_backbone

    # Required for parameters to be visible
    registration_name: stabilizer

controllers:
  # Backbone
  - filter:
      name: ''
    module:
      _target: stability.controllers.conv_backbone.ConvBackbone
      conv_kernel_size: 3
      hidden_layers: 6
      hook_target: inputs
      internal_channels: 32
      skip_connection: false
    pre_hook: true

    # Required for parameters to be visible
    registration_name: controller_backbone
