_defaults:
  - configs/train/finetune_nafnet_robust_spring.yml
input_transform:
  _target: stability.transforms.gaussian_noise.GaussianNoise
  sigma: 0.1
epochs: 20
optimizer:
  lr: 1e-4
scheduler:
  _target: torch.optim.lr_scheduler.MultiStepLR
  milestones: [ 10, 15 ]
  gamma: 0.1

# Learning curves look great
