_defaults:
  - ./_defaults.yml 
  - configs/metrics/_depth_metrics.yml
  - configs/models/depth_anything.yml
  - configs/datasets/vision_sim_val_full.yml
postprocess_transform:
  _target: instant_video_models.utils.AffineAlignPredictions
  mask_nan: true
