stabilizers:
  # One stabilizer on each Dinov2Layer with channel axis -1 (transformer)
  - filter:
      typename: Dinov2Layer
    module:
      _target: instant_video_models.stabilizers.simple_learned_stabilizer.SimpleLearnedStabilizer
      channel_axis: -1
      hook_target: output
      logits_init: 4.0

    # Required for parameters to be visible
    registration_name: stabilizer

  # One stabilizer on each DepthAnythingReassembleLayer,
  # DepthAnythingFeatureFusionLayer, and DepthAnythingDepthEstimationHead with
  # channel axis 1 (convolution)
  - filter:
      typename:
        - DepthAnythingReassembleLayer
        - DepthAnythingFeatureFusionLayer
        - DepthAnythingDepthEstimationHead
    module:
      _target: instant_video_models.stabilizers.simple_learned_stabilizer.SimpleLearnedStabilizer
      channel_axis: 1
      hook_target: output
      logits_init: 4.0

    # Required for parameters to be visible
    registration_name: stabilizer
