stabilizers:
  # One conv stabilizer on each DepthAnythingReassembleLayer,
  # DepthAnythingFeatureFusionLayer, and DepthAnythingDepthEstimationHead
  - filter:
      typename:
        - DepthAnythingReassembleLayer
        - DepthAnythingFeatureFusionLayer
        - DepthAnythingDepthEstimationHead  # Model output
    module:
      _target: stability.stabilizers.simple_recurrent_conv_stabilizer.SimpleRecurrentConvStabilizer
      conv_kernel_size: 3
      hidden_layers: 2
      hook_target: output
      internal_channels: 32

    # Required for parameters to be visible
    registration_name: stabilizer
