alpha: 0.9
stabilizers:
  # One stabilizer on each Dinov2Layer, DepthAnythingReassembleLayer,
  # DepthAnythingFeatureFusionLayer, and DepthAnythingDepthEstimationHead
  - filter:
      typename:
        - Dinov2Layer
        - DepthAnythingReassembleLayer
        - DepthAnythingFeatureFusionLayer
        - DepthAnythingDepthEstimationHead
    module:
      _target: instant_video_models.stabilizers.simple_fixed_stabilizer.SimpleFixedStabilizer
      alpha: ${....alpha}
      hook_target: output
