stabilizers:
  # One conv stabilizer on each DepthAnythingReassembleLayer,
  # DepthAnythingFeatureFusionLayer, and DepthAnythingDepthEstimationHead
  - filter:
      typename:
        - DepthAnythingReassembleLayer
        - DepthAnythingFeatureFusionLayer
        - DepthAnythingDepthEstimationHead  # Model output
    module:
      _target: stability.stabilizers.controlled_conv_ema_stabilizer.ControlledConvEMAStabilizer
      conv_kernel_size: 3
      final_bias_init: -4.0
      fusion_kernel_size: 3
      hidden_layers: 2
      hook_target: output
      internal_channel_ratio: null
      internal_channels: 32
      interpolate_mode: bilinear
      skip_connection: false
    links:
      - location: model.backbone.controller_backbone
        name: controller_backbone

    # Required for parameters to be visible
    registration_name: stabilizer

controllers:
    # Conv backbone
  - filter:
      name: model.backbone
    module:
      _target: stability.controllers.conv_backbone.ConvBackbone
      conv_kernel_size: 3
      hidden_layers: 6
      hook_target: inputs
      internal_channels: 16
      skip_connection: false
    pre_hook: true

    # Required for parameters to be visible
    registration_name: controller_backbone
