_defaults:
  - ../visualizers/image.yml
model:
  _target: instant_video_models.models.hdrnet.HDRNet
  internal_size: [ 256, 256 ]
  weights_filepath: ${_original_dir}/weights/hdrnet/local_laplacian/strong_1024.pth
  width_factor: 1
