_defaults:
  - ../visualizers/none.yml
model:
  _target: instant_video_models.models.resnet.Resnet
  input_size: [ 224, 224 ]
  n_classes: 2
  normalize_mean: [ 0.485, 0.456, 0.406 ]
  normalize_std: [ 0.229, 0.224, 0.225 ]
  weights_filepath: null
