_defaults:
  - configs/train/finetune_deeplab_viper.yml

# Fine-tune everything, not just the adapter.
freeze_initial_params: false
unfrozen_modules: []

# TODO: Try doubling the number of epochs
epochs: 60
optimizer:
  lr: 1e-4
scheduler:
  _target: torch.optim.lr_scheduler.MultiStepLR
  milestones: [ 20, 40 ]
  gamma: 0.1

# Finetune > adapter-only
# Deeplab > UPerNet
# Peak MIOU ~0.422
# Best model so far
# Use as the default base model for future segmentation experiments
