_defaults:
  - ./train_spatial_ema_stabilizer_ce.yml
  - ./_defaults_train_corruptions.yml
_name: train_spatial_ema_stabilizer_ce_elastic_transform
frame_transform:
  _target: stability.transforms.elastic_transform.ElasticTransform
  magnitude: 50.0
  smoothness: 5.0
