_defaults:
  - ./_defaults_train_stabilizers.yml
  - configs/stabilizers/deeplab/controlled_spatial.yml
epochs: 60
optimizer:
  lr: 1e-4
scheduler:
  _target: torch.optim.lr_scheduler.MultiStepLR
  milestones: [ 20, 40 ]
  gamma: 0.1
