_defaults:
  - configs/train/finetune_deeplab_viper.yml

# Only train the class adapter.
freeze_initial_params: true
unfrozen_modules:
  - class_adapter

epochs: 16
optimizer:
  lr: 1e-2
scheduler:
  _target: torch.optim.lr_scheduler.MultiStepLR
  milestones: [ 4, 8, 12 ]
  gamma: 0.1

# Finetune > adapter-only
# No overfitting
# Peak MIOU ~0.152
