_defaults:
  - ./train_spatial_ema_stabilizer_ce.yml
  - ./_defaults_train_corruptions.yml
_name: train_spatial_ema_stabilizer_ce_chunk_drop
frame_transform:
  _target: stability.transforms.chunk_drop.ChunkDrop
  chunk_size: 8
  drop_ratio: 0.1
