_defaults:
  - adversarial_model: ../models/resnet.yml
transforms:
  - _target: instant_video_models.transforms.adversarial.IterativeFGSMAttack
    model: ${adversarial_model.model}
    device: cuda
    epsilon: 0.5
    iters: 5
