_defaults:
  - ./_defaults_train_stabilizers.yml
  - configs/stabilizers/hdrnet/controlled_spatial.yml
epochs: 20
optimizer:
  lr: 1e-4
scheduler:
  _target: torch.optim.lr_scheduler.MultiStepLR
  milestones: [ 10, 15 ]
  gamma: 0.1
