_defaults:
  - ./_defaults_train_stabilizers.yml
  - configs/stabilizers/hdrnet/learned_ema_stabilizer.yml

# Use lambda to create a subdir instead of appending to the name.
_name: train_learned_ema_stabilizer
_output_dir: outputs/${_config_dir}/${_name}/${lambda}/${_datetime}
checkpoint_search_path: ${_original_dir}/outputs/${_config_dir}/${_name}/${lambda}

epochs: 20
optimizer:
  lr: 1e-3
scheduler:
  _target: torch.optim.lr_scheduler.MultiStepLR
  milestones: [ 10, 15 ]
  gamma: 0.1
