stabilizers:
  # Two composed stabilizers on each NAFBlock
  - filter:
      typename: NAFBlock
    module:
      _target: instant_video_models.stabilizers.controlled_conv_stabilizer.ControlledConvStabilizer
      conv_kernel_size: 3
      exclude_feature_inputs: true
      final_bias_init: -4.0
      fusion_kernel_size: 1
      hidden_layers: 2
      hook_target: output
      internal_channels: 64
      interpolate_mode: bilinear
    links:
      - location: module.controller_backbone_1
        name: controller_backbone
    registration_name: ensemble_1
  - filter:
      typename: NAFBlock
    module:
      _target: instant_video_models.stabilizers.controlled_conv_stabilizer.ControlledConvStabilizer
      conv_kernel_size: 3
      exclude_feature_inputs: true
      final_bias_init: -4.0
      fusion_kernel_size: 1
      hidden_layers: 2
      hook_target: output
      internal_channels: 64
      interpolate_mode: bilinear
    links:
      - location: module.controller_backbone_2
        name: controller_backbone
    registration_name: ensemble_2

  # Two composed stabilizers on the output
  - filter:
      name: module
    module:
      _target: instant_video_models.stabilizers.controlled_conv_stabilizer.ControlledConvStabilizer
      conv_kernel_size: 3
      exclude_feature_inputs: true
      final_bias_init: -4.0
      fusion_kernel_size: 1
      hidden_layers: 2
      hook_target: output
      internal_channels: 64
      interpolate_mode: bilinear
    links:
      - location: module.controller_backbone_1
        name: controller_backbone
    registration_name: ensemble_1
  - filter:
      name: module
    module:
      _target: instant_video_models.stabilizers.controlled_conv_stabilizer.ControlledConvStabilizer
      conv_kernel_size: 3
      exclude_feature_inputs: true
      final_bias_init: -4.0
      fusion_kernel_size: 1
      hidden_layers: 2
      hook_target: output
      internal_channels: 64
      interpolate_mode: bilinear
    links:
      - location: module.controller_backbone_2
        name: controller_backbone
    registration_name: ensemble_2

controllers:
  # Two parallel backbones
  - filter:
      name: module
    module:
      _target: instant_video_models.controllers.conv_backbone.ConvBackbone
      conv_kernel_size: 3
      hidden_layers: 6
      hook_target: inputs
      internal_channels: 32
    pre_hook: true
    registration_name: controller_backbone_1
  - filter:
      name: module
    module:
      _target: instant_video_models.controllers.conv_backbone.ConvBackbone
      conv_kernel_size: 3
      hidden_layers: 6
      hook_target: inputs
      internal_channels: 32
    pre_hook: true
    registration_name: controller_backbone_2
