stabilizers:
  # One stabilizer on each NAFBlock
  - filter:
      typename: NAFBlock
    module:
      _target: stability.stabilizers.ema_stabilizer.EMAStabilizer
      alpha: ${....alpha}
      hook_target: output

  # One stabilizer on the output
  - filter:
      name: module
    module:
      _target: stability.stabilizers.ema_stabilizer.EMAStabilizer
      alpha: ${....alpha}
      hook_target: output

# Override this value to test degrees of stabilization.
alpha: 0.9
