alpha: 0.9
stabilizers:
  # One stabilizer on each NAFBlock
  - filter:
      typename: NAFBlock
    module:
      _target: instant_video_models.stabilizers.simple_fixed_stabilizer.SimpleFixedStabilizer
      alpha: ${....alpha}
      hook_target: output

  # One stabilizer on the output
  - filter:
      name: module
    module:
      _target: instant_video_models.stabilizers.simple_fixed_stabilizer.SimpleFixedStabilizer
      alpha: ${....alpha}
      hook_target: output
