_defaults:
  - ./_defaults.yml
  - ./_finetune.yml
  - configs/metrics/_video_metrics.yml
  - configs/models/hdrnet-laplacian.yml
  - nfs_laplacian_strong_train_chunk_1_batchable: configs/datasets/nfs_laplacian_strong_train_chunk_1_batchable.yml
  - nfs_laplacian_strong_val: configs/datasets/nfs_laplacian_strong_val.yml
train_batch_size: 8
train_dataset: ${nfs_laplacian_strong_train_chunk_1_batchable.dataset}
train_repeats: 200
val_batch_size: 1
val_dataset: ${nfs_laplacian_strong_val.dataset}
