_defaults:
  - ./_defaults.yml 
  - ./_train_stabilizers.yml
  - configs/metrics/_video_metrics.yml
  - configs/models/nafnet.yml
  - davis_train_chunk_8: configs/datasets/davis_train_chunk_8.yml
  - davis_val: configs/datasets/davis_val.yml
_output_dir: outputs/${_config_dir}/${_name}/${lambda}/${_datetime}
checkpoint_search_path: ${_original_dir}/outputs/${_config_dir}/${_name}/${lambda}
lambda: 0.4
train_batch_size: 1
train_dataset: ${davis_train_chunk_8.dataset}
train_repeats: 40
val_batch_size: 1
val_dataset: ${davis_val.dataset}
