_defaults:
  - ./_defaults.yml
  - ./_train_stabilizers.yml
  - configs/metrics/_video_metrics.yml
  - configs/models/hdrnet-laplacian.yml
  - nfs_laplacian_moderate_train_chunk_8: configs/datasets/nfs_laplacian_moderate_train_chunk_8.yml
  - nfs_laplacian_moderate_val: configs/datasets/nfs_laplacian_moderate_val.yml
train_batch_size: 1
train_dataset: ${nfs_laplacian_moderate_train_chunk_8.dataset}
train_repeats: 50
val_batch_size: 1
val_dataset: ${nfs_laplacian_moderate_val.dataset}
