_defaults:
  - ./_defaults.yml 
  - ./_train_stabilizers.yml
  - configs/metrics/_segmentation_metrics.yml
  - configs/models/deeplab-viper.yml
  - viper_train_chunk_8: configs/datasets/viper_train_chunk_8.yml
  - viper_val: configs/datasets/viper_val.yml
_output_dir: outputs/${_config_dir}/${_name}/${lambda}/${_datetime}
checkpoint_search_path: ${_original_dir}/outputs/${_config_dir}/${_name}/${lambda}
lambda: 0.4
loss:
  loss_metric:
    _target: instant_video_models.losses.cross_entropy.CrossEntropy
    epsilon: 1e-6
train_batch_size: 1
train_dataset: ${viper_train_chunk_8.dataset}
train_repeats: 40
val_batch_size: 1
val_dataset: ${viper_val.dataset}
