_defaults:
  - ./_defaults.yml
  - ./_train_stabilizers.yml
  - configs/metrics/_video_metrics.yml
  - configs/models/nafnet.yml
  - robust_spring_train_chunk_8: configs/datasets/robust_spring_train_chunk_8.yml
  - robust_spring_val: configs/datasets/robust_spring_val.yml
train_batch_size: 1
train_dataset: ${robust_spring_train_chunk_8.dataset}
train_repeats: 50
val_batch_size: 1
val_dataset: ${robust_spring_val.dataset}
