dataset:
  _target: instant_video_models.datasets.davis.DAVIS
  location: ${_original_dir}/data/davis_2017
  ending_frame: null
  frame_transform: null
  random_chunk_size: null
  random_crop_size: null
  split: train
