dataset:
  _target: instant_video_models.datasets.robust_spring.SpringCorrupted
  location: ${_original_dir}/data/robust_spring
  clean_transform: null
  corrupted_transform: null
  corruption_type: null
  random_chunk_size: null
  random_crop_size: null
  split_subset: null
