dataset:
  _target: instant_video_models.datasets.viper.VIPERSegmentation
  location: ${_original_dir}/data/viper
  ending_frame: null
  frame_transform: null
  random_chunk_size: null
  random_crop_size: null
  split: train
